name: cafe_hub_flutter
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  naver_map_plugin:
    git: https://github.com/LBSTECH/naver_map_plugin.git
  flutter_svg: ^1.1.4
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  flutter_native_splash: ^2.2.8
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/splash.png